apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testrepo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:DariuszPrzysiecki/testrepo.git' # Updated to use SSH
    targetRevision: HEAD
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
